export const COLOMBIAN_DEPARTMENTS = [
  'Amazonas',
  'Antioquia',
  'Arauca',
  'Atlantico',
  'Bogota D.C.',
  'Bolivar',
  'Boyaca',
  'Caldas',
  'Caqueta',
  'Casanare',
  'Cauca',
  'Cesar',
  'Choco',
  'Cordoba',
  'Cundinamarca',
  'Guainia',
  'Guaviare',
  'Huila',
  'La Guajira',
  'Magdalena',
  'Meta',
  'Narino',
  'Norte de Santander',
  'Putumayo',
  'Quindio',
  'Risaralda',
  'San Andres y Providencia',
  'Santander',
  'Sucre',
  'Tolima',
  'Valle del Cauca',
  'Vaupes',
  'Vichada',
] as const;

export type ColombianDepartment = (typeof COLOMBIAN_DEPARTMENTS)[number];

export const MAJOR_CITIES = [
  { name: 'Bogota', department: 'Bogota D.C.' },
  { name: 'Medellin', department: 'Antioquia' },
  { name: 'Cali', department: 'Valle del Cauca' },
  { name: 'Barranquilla', department: 'Atlantico' },
  { name: 'Cartagena', department: 'Bolivar' },
  { name: 'Bucaramanga', department: 'Santander' },
  { name: 'Pereira', department: 'Risaralda' },
  { name: 'Santa Marta', department: 'Magdalena' },
  { name: 'Manizales', department: 'Caldas' },
  { name: 'Ibague', department: 'Tolima' },
  { name: 'Cucuta', department: 'Norte de Santander' },
  { name: 'Villavicencio', department: 'Meta' },
  { name: 'Armenia', department: 'Quindio' },
  { name: 'Pasto', department: 'Narino' },
  { name: 'Neiva', department: 'Huila' },
  { name: 'Monteria', department: 'Cordoba' },
  { name: 'Popayan', department: 'Cauca' },
  { name: 'Valledupar', department: 'Cesar' },
  { name: 'Tunja', department: 'Boyaca' },
  { name: 'Sincelejo', department: 'Sucre' },
] as const;

export type MajorCity = (typeof MAJOR_CITIES)[number];
